name: Pylint

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python "3.12.4"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0301,R0914,R0912,R0915,E0401
# --output=lint.txt || true
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: lint.txt
#        path: lint.txt
